name: build-macos

on:
  push:
    branches:
      - testmac
  pull_request:
    branches:
      - testmac

env:
  GO111MODULE: off

jobs:
  test:
    name: build-macos
    strategy:
      fail-fast: false
      matrix:
        go: [1.16.x]
        os: [macos-latest]
    runs-on: ${{ matrix.os}}
    steps:
      - name: install golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: checkout code
        uses: actions/checkout@v2
      - name: go env
        run: |
          printf "$(go version)\n"
          printf "\n\ngo environment:\n\n"
          go get -u github.com/lesismal/nbio/...
          go get -u github.com/sasha-s/go-deadlock
          ulimit -n 30000
          go env
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: go test
        run: go test -covermode=atomic -v -timeout 60s -coverprofile="./coverage"
